openshift:
  enabled: true
  securityContext:
    runAsUser: 1001610000
    runAsGroup: 1001610000
    fsGroup: 1001610000
  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false

server:
  policyRepoUrl: ""
  policyRepoSshKey: null
  policyRepoClonePath: "/tmp/opal/policy"
  policyRepoMainBranch: master
  pollingInterval: 30

  dataConfigSources:
    # Option #1 - No data sources
    # config:
    #   entries: []

    # Option #2 - Dynamically get data sources
    external_source_url: "https://opal-pip-catalog-api-gov-bc-ca.dev.api.gov.bc.ca/entries"

    # Option #3 - Example static data sources (endpoint is empty by default)
    # config:
    #   entries:
    #     - url: http://opal-server:7002/policy-data
    #       topics: ["policy_data"]
    #       dst_path: "/static"

    # Option #4 - Leave config empty and instead supply using the OPAL_DATA_CONFIG_SOURCES environment variable through env or secret
    config: null

  extraEnv:
    OPAL_ALL_DATA_URL: "http://opal-server:7002/policy-data"
    OPAL_POLICY_SOURCE_TYPE: "API"
    OPAL_POLICY_BUNDLE_URL: http://opal-policies
    OPAL_POLICY_REPO_POLLING_INTERVAL: 30
    OPAL_LOG_LEVEL: DEBUG
    OPAL_LOG_COLORIZE: "false"
    OPAL_AUTH_JWT_ISSUER: "https://opal-api-gov-bc-ca.dev.api.gov.bc.ca"

  secrets:
    - opal-server

client:
  enabled: false

image:
  server:
    tag: "0.9.5"
