name: 'Send review reminders'
on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          days-before-pr-stale: 4
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
          days-before-close: -1 # don't close issues or PRs