#!/usr/bin/env bash
# Regenerate chart.yaml with the project bundled as a base64-encoded tar.gz.
# Run from any cwd: bash scripts/build-chart.sh
set -euo pipefail

cd "$(dirname "$0")/.."

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

tar -czf "$TMP/bundle.tar.gz" \
  main.ts \
  types.ts \
  config.yaml \
  metrics-queries.yaml \
  deno.json \
  deno.lock \
  components \
  pages \
  lib \
  public/bc_logo_header.svg \
  public/vendor \
  public/css

BUNDLE_BYTES=$(wc -c < "$TMP/bundle.tar.gz" | tr -d ' ')

# Wrap base64 to 76 cols and indent six spaces for the YAML literal block.
B64=$(base64 < "$TMP/bundle.tar.gz" | fold -w 76 | sed 's/^/      /')

cat > chart.yaml <<EOF
# AUTO-GENERATED by scripts/build-chart.sh — do not edit by hand.
# The bundle below is a tar.gz of the Deno app, base64-encoded; rerun the
# script after changing source files to refresh it.
replicaCount: 2

rollingUpdate:
  maxUnavailable: 50%
  maxSurge: 50%

image:
  repository: denoland/deno
  tag: 2.7.10
  pullPolicy: IfNotPresent

persistence:
  deno-dir:
    mountPath: /deno-dir
  work:
    mountPath: /work

config:
  - filename: bundle.tar.gz.b64
    mountPath: /app/bundle.tar.gz.b64
    contents: |
$B64

command:
  - sh

args:
  - -c
  - |
    set -e
    mkdir -p /work
    base64 -d /app/bundle.tar.gz.b64 > /tmp/bundle.tar.gz
    cd /work
    tar -xzf /tmp/bundle.tar.gz
    exec deno run \\
      --allow-net=:8000,pzgw.api.gov.bc.ca:443,pzgw.test.api.gov.bc.ca:443,pzgw.dev.api.gov.bc.ca:443,pzgw-api-gov-bc-ca.dev.api.gov.bc.ca:443,pzgw-api-gov-bc-ca.test.api.gov.bc.ca:443,sdx-api-gov-bc-ca.dev.api.gov.bc.ca:443,sdx-api-gov-bc-ca.test.api.gov.bc.ca:443,sdx.gov.bc.ca:443,api-gov-bc-ca.dev.api.gov.bc.ca:443,api-gov-bc-ca.test.api.gov.bc.ca:443,pubsub-kafka:80,thanos-query:9090,thanos-prom-prometheus-server:80,public-bodies.dev.api.gov.bc.ca:443,*.loginproxy.gov.bc.ca:443,authz-apps-gov-bc-ca.dev.api.gov.bc.ca:443,authz-apps-gov-bc-ca.test.api.gov.bc.ca:443,www2.gov.bc.ca:443,authz.apps.gov.bc.ca:443,api.gov.bc.ca:443 \\
      --allow-env=PORT,SDX_API_BASE,SDX_KEYSET_BASE,SDX_API_ROOT,NODE_ENV,LOG_STREAM_URL,JWKS_URL,PROMETHEUS_URL,PUBLIC_BODIES_API,OIDC_ISSUER,OIDC_CLIENT_ID,OIDC_CLIENT_SECRET,SESSION_SECRET,OIDC_REDIRECT_URI,OIDC_SCOPES,READABLE_STREAM,READABLE_STREAMS,WRITABLE_STREAMS,URL,URL_SEARCH_PARAMS,URL_SEARCH_PARAMS_ITERATOR,URL_SEARCH_PARAMS_SORTED_ITERATOR,URL_SEARCH_PARAMS_VALUES,GRACEFUL_FS_PLATFORM,TEST_GRACEFUL_FS_GLOBAL_PATCH,BLUEBIRD_* \\
      --allow-read \\
      --allow-write=/tmp,/work/public/fonts \\
      main.ts

env:
  PORT:
    value: "8000"

  SDX_KEYSET_BASE:
    value: "https://pzgw-api-gov-bc-ca.dev.api.gov.bc.ca/keysets"
  SDX_API_BASE:
    value: "https://api-gov-bc-ca.dev.api.gov.bc.ca/ds/api/sdx/v1/catalog"
  SDX_API_ROOT:
    value: "https://api-gov-bc-ca.dev.api.gov.bc.ca/ds/api/sdx/v1"
  LOG_STREAM_URL:
    value: "http://pubsub-kafka/sdx/messages?history=10"
  # JWKS sources are configured per environment in config.yaml
  # (environments[].jwks_urls). Set JWKS_URL only to override with a flat list.
  PROMETHEUS_URL:
    value: "http://thanos-prom-prometheus-server"
  PUBLIC_BODIES_API:
    value: "https://public-bodies.dev.api.gov.bc.ca/v1"

  OIDC_ISSUER:
    value: "https://authz-apps-gov-bc-ca.dev.api.gov.bc.ca/auth/realms/aps"
  OIDC_CLIENT_ID:
    value: "gwa"
  OIDC_CLIENT_SECRET:
    value: "<secret>"
  SESSION_SECRET:
    value: "<random 32+ byte string>"
  OIDC_REDIRECT_URI:
    value: "https://sdx-api-gov-bc-ca.dev.api.gov.bc.ca/auth/callback"

EOF

echo "chart.yaml regenerated; bundle is ${BUNDLE_BYTES} bytes (tar.gz)."
