name: 'Send review reminders'
description: 'Sends reminders for pull requests that need review'
runs:
  using: "composite"
  steps:
    - uses: actions/stale@v9
      with:
        days-before-issue-stale: -1 # don't mark issues stale
        # stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
        days-before-pr-stale: 4
        stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
        days-before-close: -1 # don't close issues or PRs