name: 'Send PR review reminders'
description: "Reminds pending reviewers on GitHub pull requests by tagging them in comments."
author: "API Program Services Team"
inputs:
  dry_run:
    description: "Enable dry-run mode (no comments will be posted)"
    required: false
    default: "false"
outputs:
  result:
    description: "Summary of actions taken"
runs:
  using: "composite"
  steps:
    - name: Run reminder script
      shell: node
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: ${{ inputs.dry_run }}
      run: |
        node script.js
