{{ if .Values.shared.fluentbit.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sdx-fluentbit
  labels:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sdx-edge
      app.kubernetes.io/component: fluentbit
      app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
  template:
    metadata:
      creationTimestamp: null
      labels:
        DataClass: Low
        app.kubernetes.io/name: sdx-edge
        app.kubernetes.io/component: fluentbit
        app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              memory: 700Mi
            requests:
              cpu: 150m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: fluentbit
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          securityContext: {}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
            - name: input
              containerPort: 24224
              protocol: TCP
            - name: metrics
              containerPort: 2021
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-vol
              readOnly: true
              mountPath: /fb/fluentbit.yaml
              subPath: fluentbit.yaml
            - name: config-vol
              readOnly: true
              mountPath: /fb/parsers.conf
              subPath: parsers.conf
            - name: sdx-edge-client-cert
              mountPath: /etc/secrets/sdx-edge-client-cert
            - name: sdx-ca
              mountPath: /etc/secrets/sdx-ca


          terminationMessagePolicy: File
          image: 'docker.io/fluent/fluent-bit:4.1.1'
          args:
            - '--config=/fb/fluentbit.yaml'
      volumes:
        - name: config-vol
          configMap:
            name: sdx-fluentbit-config
            defaultMode: 420
        - name: sdx-edge-client-cert
          secret:
            secretName: {{ include "sdx-edge.fullname" . }}-client
        - name: sdx-ca
          secret:
            secretName: sdx-public-ca

      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 33%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sdx-fluentbit-config
  labels: {}
data:
  fluentbit.yaml: |-
    service:
      flush: 3
      daemon: off
      log_level: info
      http_server: On
      http_listen: 0.0.0.0
      http_port: 2020

    pipeline:
      inputs:
        - name: http
          listen: 0.0.0.0
          port: 24224
          buffer_chunk_size: 1M
          buffer_max_size: 20M
          mem_buf_limit: 100MB

        # - name: fluentbit_metrics
        #   tag: internal_metrics
        #   scrape_interval: 2

      outputs:
        # - name: stdout
        #   match: "*"
        #   format: json_lines

        # - name: prometheus_exporter
        #   match: internal_metrics
        #   host: 0.0.0.0
        #   port: 2021

        - name: http
          match: "*"
          host: {{ index .Values.sdx_aggregator_url_by_env .Values.environment }}
          port: 443
          tls.vhost: {{ index .Values.sdx_aggregator_url_by_env .Values.environment }}
          format: json
          tls: on
          tls.verify: off
          tls.ca_file: /etc/secrets/sdx-ca/ca.crt
          tls.crt_file: /etc/secrets/sdx-edge-client-cert/tls.crt
          tls.key_file: /etc/secrets/sdx-edge-client-cert/tls.key

  parsers.conf: |-
    [MULTILINE_PARSER]
      name        json_array
      type        regex
      flush_timeout 1000
      # Regex to capture the opening and closing brackets of a JSON array
      rule        "start_state"      /^\s*\[\s*$/   "cont"
      rule        "cont"             /^\s*\]\s*$/   "end_state"
      rule        "end_state"        /^.*$/         "cont"
---
apiVersion: v1
kind: Service
metadata:
  name: sdx-log-aggregator
  labels:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: fluentbit
    enable-metrics: "true"
spec:
  type: ClusterIP
  ports:
  - name: forwarder-port
    port: 24224
    targetPort: 24224
    protocol: TCP
  selector:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
{{ end }}