apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "sdx-edge.fullname" . }}"
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    data-plane: "{{ include "sdx-edge.fullname" . }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "sdx-edge.fullname" . }}"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
