{{ if .Values.kong.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdx-edge.fullname" . }}
  labels:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    runtime-group: "{{ include "sdx-edge.fullname" . }}"
    {{ include "sdx-edge.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: sdx-edge
      app.kubernetes.io/component: kong
      app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      annotations:
        kuma.io/gateway: "enabled"
        traffic.sidecar.istio.io/includeInboundPorts: ""
      labels:
        DataClass: Medium
        app.kubernetes.io/name: sdx-edge
        app.kubernetes.io/component: kong
        app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
        runtime-group: "{{ include "sdx-edge.fullname" . }}"
        {{ include "sdx-edge.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      initContainers:
      - name: clear-stale-pid
        image: ghcr.io/bcgov/aps-devops/sdx-access-point:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        command:
        - "rm"
        - "-vrf"
        - "$KONG_PREFIX/pids"
        volumeMounts:
        - name: prefix-dir
          mountPath: /kong_prefix/
        - name: tmp-dir
          mountPath: /tmp
      containers:
      - name: "proxy"
        image: ghcr.io/bcgov/aps-devops/sdx-access-point:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_CLUSTER_DP_LABELS
          value: "runtime-group:{{ include "sdx-edge.fullname" . }},endpoint:{{- .Values.route.host }},role:sdx-access-point"
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: {{ .Values.sdx_control_url | quote }}
        - name: KONG_NGINX_PROXY_SSL_VERIFY_CLIENT
          value: "{{- if .Values.mtls_required }}on{{- else }}optional{{- end }}"
        - name: KONG_NGINX_PROXY_SSL_VERIFY_DEPTH
          value: "{{- if .Values.mtls_required }}3{{- else }}1{{- end }}"
        - name: KONG_PROXY_ACCESS_LOG
          value: "off"
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, [::]:8000, 0.0.0.0:8443 http2 ssl, [::]:8443 http2 ssl, 0.0.0.0:3443 http2 ssl
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: '/etc/ssl/certs/ca-certificates.crt,/etc/secrets/sdx-public-ca/ca.crt'

        {{ if .Values.aws.enabled }}
        - name: AWS_REGION
          value: "{{ .Values.aws.region }}"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "sdx-edge.fullname" . }}-aws
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "sdx-edge.fullname" . }}-aws
              key: secret_access_key
        {{ end }}
        lifecycle:
          preStop:
            exec:
              command:
              - kong
              - quit
              - --wait=15
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-tls
          containerPort: 8443
          protocol: TCP
        - name: status
          containerPort: 8100
          protocol: TCP
        volumeMounts:
          - name: prefix-dir
            mountPath: /kong_prefix/
          - name: tmp-dir
            mountPath: /tmp
          - name: sdx-edge-server-cert
            mountPath: /etc/secrets/sdx-edge-server-cert
          - name: sdx-edge-client-cert
            mountPath: /etc/secrets/sdx-edge-signing-cert
          - name: sdx-edge-client-cert
            mountPath: /etc/secrets/sdx-edge-client-cert
          - name: sdx-edge-client-cert
            mountPath: /etc/secrets/sdx-edge-cluster-cert
          - name: sdx-edge-client-cert
            mountPath: /etc/secrets/kong-upstream-jwt
          - name: sdx-public-ca
            mountPath: /etc/secrets/sdx-public-ca
          - name: sdx-edge-ca
            mountPath: /etc/secrets/sdx-edge-ca
          - name:  kong-nginx-proxy-include
            mountPath: /etc/secrets/kong-nginx-proxy-include
          - mountPath: /.luarocks
            name: dotluarocks
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status/ready
            port: status
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: status
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi 
      securityContext:
        {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: prefix-dir
          emptyDir:
            sizeLimit: 256Mi
        - name: tmp-dir
          emptyDir:
            sizeLimit: 1Gi
        - name: sdx-edge-client-cert
          secret:
            secretName: {{ include "sdx-edge.fullname" . }}-client
        - name: sdx-edge-server-cert
          secret:
            secretName: {{ include "sdx-edge.fullname" . }}-server
        - name: sdx-public-ca
          secret:
            secretName: sdx-public-ca
        - name: sdx-edge-ca
          secret:
            secretName: sdx-edge-ca
        - name: kong-nginx-proxy-include
          secret:
            secretName: {{ include "sdx-edge.fullname" . }}-proxy-include
        - emptyDir: {}
          name: dotluarocks
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "sdx-edge.fullname" . }}"
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    runtime-group: "{{ include "sdx-edge.fullname" . }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "sdx-edge.fullname" . }}"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdx-edge.fullname" . }}
  labels:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    enable-metrics: "true"
spec:
  type: ClusterIP
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-tls
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
{{ end }}