kind: Secret
apiVersion: v1
metadata:
  name: {{ include "sdx-edge.fullname" . }}-server
data:
  tls.crt: {{ .Values.tls.server.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.server.key | b64enc | quote }}
type: kubernetes.io/tls
---
{{ if .Values.tls.client.bootstrap.token }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "sdx-edge.fullname" . }}-bootstrap
data:
  token: {{ .Values.tls.client.bootstrap.token | b64enc | quote }}
type: Opaque
---
{{ end }}
{{ if .Values.shared.ca_secret }}
kind: Secret
apiVersion: v1
metadata:
  name: sdx-edge-ca
data:
  ca.crt: {{ .Values.tls.ca | b64enc | quote }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: kong-nginx-proxy-include
data:
  config: {{ .Values.nginx_conf | b64enc | quote }}
type: Opaque
{{ end }}