kind: Secret
apiVersion: v1
metadata:
  name: {{ include "sdx-edge.fullname" . }}-proxy-include
data:
  config: {{ .Values.nginx_conf | b64enc | quote }}
type: Opaque

{{ if .Values.tls.client.bootstrap.token }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "sdx-edge.fullname" . }}-bootstrap
data:
  token: {{ .Values.tls.client.bootstrap.token | b64enc | quote }}
type: Opaque
{{ end }}

{{ if .Values.shared.ca_secret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: sdx-public-ca
data:
  ca.crt: {{ .Values.tls.public_ca | b64enc | quote }}
type: Opaque
{{ end }}
