apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdx-edge.fullname" . }}
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
    data-plane: "{{ include "sdx-edge.fullname" . }}"
    enable-metrics: "true"
spec:
  type: ClusterIP
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-tls
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: sdx-edge
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: "{{ include "sdx-edge.fullname" . }}"
