replicaCount: 1

rollingUpdate:
  maxUnavailable: 100%
  maxSurge: 100%

image:
  repository: denoland/deno
  tag: 2.7.10
  pullPolicy: IfNotPresent

persistence:
  deno-dir:
    mountPath: /deno-dir

config:
  - filename: main.ts
    mountPath: /app/main.ts

command:
  - deno

args:
  - run
  - --allow-net=:8000,kafka:9092,*.kafka-controller-headless.b8840c-dev.svc.cluster.local,*.kafka-controller-headless.b8840c-test.svc.cluster.local,*.kafka-controller-headless.b8840c-prod.svc.cluster.local
  - --allow-env=KAFKA_BROKERS,NODE_ENV,KAFKAJS_*
  - /app/main.ts

env:
  KAFKA_BROKERS:
    value: kafka:9092
