name: SDX Brochure UI

on:
  push:
    branches: [feature/*]

jobs:
  build-brochure-ui:
    uses: ./.github/workflows/.build.yml
    permissions:
      contents: read
      packages: write # 🚀 Crucial permission needed to push to ghcr.io
    with:
      name: sdx-ui
      context: ./sdx/brochure-ui
